# Generated by Django 3.0.2 on 2021-10-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20211018_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='None', max_length=200, verbose_name='Nombre de usuario'),
        ),
    ]
