# Generated by Django 3.0.2 on 2021-10-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20211018_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Nombre de Usuario'),
        ),
    ]
