# Generated by Django 3.0.2 on 2021-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20211018_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='usuario_administrador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de usuario'),
        ),
    ]
