# Generated by Django 3.0.2 on 2021-10-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20211018_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_root',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_tecnico_hardware',
            field=models.BooleanField(default=False),
        ),
    ]
