# Generated by Django 3.0.2 on 2021-10-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20211019_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cc',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='C.C'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
