# Generated by Django 3.0.2 on 2021-10-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20211019_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
