# Generated by Django 3.0.2 on 2021-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
