# Generated by Django 3.0.2 on 2021-10-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20211019_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
