# Generated by Django 3.0.2 on 2021-11-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_auto_20211024_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_actual', models.FloatField()),
                ('fecha_limite', models.FloatField()),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Token Email',
                'verbose_name_plural': 'Tokens Email',
            },
        ),
    ]
